### ISSUE TITLE
blank results

### ISSUE THREAD

**Issue by ThomasGHenry** [chrsm/impulse.nvim#9]
in lazyvim
 
`.config/nvim/lua/plugins/notion.lua`
```
return {
    "chrsm/impulse.nvim",
    dependencies = { "nvim-lua/plenary.nvim", "nvim-telescope/telescope.nvim" },
    config = function()
        require("impulse").setup({})
    end,
}
```

`.config/nvim/lua/config/keymaps.lua`
```
vim.keymap.set("n", "<leader>vs", require("impulse").menu_search)
vim.keymap.set("n", "<leader>vl", require("impulse").follow_link)
```

in fish

`set -Ux NOTION_SECRET secret_xxxxxxxxx....`

the keybindings open the search, but the results are always blank.

**Comment by chrsm** [comment]
Have you added your connection as mentioned in the [README](https://github.com/chrsm/impulse.nvim#before-installing)? You might have to give the plugin access to a higher-up page than you have already.

![image](https://github.com/chrsm/impulse.nvim/assets/1082451/8dcf5819-6432-40ed-b959-f850a12ce088)

**Comment by ThomasGHenry** [comment]
Thanks! 

I hadn't. Now I have. 

Same results. 

I'm content to leave it there though. Read-only defeats the purpose for me. 

It was fun to dream. Thanks again!
